### ISSUE TITLE
Rebuild image with php 8.2 for latest Moodle version

### ISSUE THREAD

**Issue by fermion2020** [tiredofit/docker-moodle#1]
**Description of the feature**

The minimum PHP version has increased since Moodle 4.1. PHP 8.2.x, so PHP 7.4 doesn't fit anymore.

**Benftits of feature**

The image will have a working state.

**Additional context**

**Comment by tiredofit** [comment]
`4.3.0` will give you PHP `8.2` as a base and for new installs provide Moodle `4.4`. Enjoy!

**Comment by tiredofit** [comment]
Now `4.3.1` due to build issues
